---
- name: Converge
  hosts: all
  vars_files:
    - vars.yml
  vars:
    keycloak_quarkus_show_deprecation_warnings: false
    keycloak_quarkus_version: 26.0.7
  roles:
    - role: keycloak_quarkus
