---
- name: Include firewall config tasks
  ansible.builtin.include_tasks:
    file: firewalld.yml
    apply:
      tags:
        - firewall
  when: keycloak_configure_firewalld
  tags:
    - firewall
