---
keycloak: # noqa var-naming this is an internal dict of interpolated values
  home: "{{ keycloak_quarkus_home }}"
  config_dir: "{{ keycloak_quarkus_config_dir }}"
  bundle: "{{ keycloak_quarkus_archive }}"
  service_name: "keycloak"
  health_url: "{{ keycloak_quarkus_health_check_url | default(keycloak_quarkus_hostname ~ '/' ~ (keycloak_quarkus_health_check_url_path | default('realms/master/.well-known/openid-configuration'))) }}"
  cli_path: "{{ keycloak_quarkus_home }}/bin/kcadm.sh"
  service_user: "{{ keycloak_quarkus_service_user }}"
  service_group: "{{ keycloak_quarkus_service_group }}"
  offline_install: "{{ keycloak_quarkus_offline_install }}"
  config_key_store_enabled: "{{ keycloak_quarkus_config_key_store_password != '' }}"
  log:
    file: "{{ keycloak_quarkus_home }}/{{ keycloak_quarkus_log_file }}"
    level: "{{ keycloak_quarkus_log_level }}"
    format: "{{ keycloak_quarkus_log_format }}"
  bootstrap_mnemonic: "# ansible-middleware/keycloak: bootstrapped"
