---
- name: "Configure sysconfig file for {{ keycloak.service_name }} service"
  become: "{{ keycloak_install_requires_become | default(true) }}"
  ansible.builtin.template:
    src: keycloak-sysconfig.j2
    dest: "{{ keycloak_quarkus_sysconf_file }}"
    owner: root
    group: root
    mode: '0640'
  vars:
    keycloak_sys_pkg_java_home: "{{ keycloak_quarkus_pkg_java_home }}"
  notify:
    - restart keycloak

- name: "Configure systemd unit file for keycloak service"
  ansible.builtin.template:
    src: keycloak.service.j2
    dest: /etc/systemd/system/keycloak.service
    owner: root
    group: root
    mode: '0644'
  become: "{{ keycloak_install_requires_become | default(true) }}"
  register: systemdunit
  notify:
    - restart keycloak
