---
- name: Prepare
  hosts: all
  gather_facts: yes
  tasks:
    - name: Install sudo
      ansible.builtin.apt:
        name:
          - sudo
          - openjdk-21-jdk-headless
          - iproute2
