---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      debug_verbosity:
        description: 'ANSIBLE_VERBOSITY envvar value'
        required: false
  schedule:
    - cron: '15 6 * * *'

jobs:
  ci:
    uses: ansible-middleware/github-actions/.github/workflows/cish.yml@main
    secrets: inherit
    with:
      fqcn: 'middleware_automation/keycloak'
      debug_verbosity: "${{ github.event.inputs.debug_verbosity }}"
      molecule_tests: >-
        [ "debian", "quarkus", "quarkus_ha", "quarkus_ha_remote" ]
      podman_tests_current: >-
        [ "default", "quarkus_devmode", "quarkus_upgrade" ]
      podman_tests_next: >-
        [ "default", "quarkus_devmode", "quarkus_upgrade" ]
